### ISSUE TITLE
REX_VAR_SPEED_UP[] funktioniert nicht

### ISSUE THREAD

**Issue by iceman-fx** [alexplusde/speed_up#24]
Hi,
ich habe speed_up bei einem Projekt installiert und zum ersten Mal den Platzhalter zur Ausgabe der Links im head-Bereich eingefügt.
Leider wird dieser nicht übersetzt und steht nach wie vor als Text drin.

![Unbenannt](https://user-images.githubusercontent.com/4291047/192987397-f579489a-eac4-45a1-9346-e95e3f2b4f6a.PNG)

**Comment by alxndr-w** [comment]
Bitte mal REX_SPEED_UP[]  probieren
