### ISSUE TITLE
Seitenstartartikel kein Artikel in der Hauptebene

### ISSUE THREAD

**Issue by ynamite** [alexplusde/speed_up#30]
Ich habe speed_up testweise installiert und den PHP Code wie in der Installationsanleitung eingefügt, aber bei mir wird nirgends etwas ausgegeben, obwohl das Profil auf "automatisches prefetching" eingestellt ist und alle Artikel auf "prefetching erlauben" eingestellt sind.

Verpasse ich was bzw. macht das Addon weitgehend alles automatisch?

**Comment by ynamite** [comment]
Ping

**Comment by ynamite** [comment]
Alex?

**Comment by ynamite** [comment]
Jetzt ist mir klar wieso sich nichts tut, das Addon erwartet, dass der Seitenstartartikel ein Artikel in der Hauptebene ist.
Wenn wie in meinem Fall eine Kategorie, dann tut sich gar nichts.
Habe nun ein paar Anpassungen vorgenommen, nun scheint's zu klappen.

**Comment by alxndr-w** [comment]
Ich habe das Szenario auch in 1-2 Projekten und meine, dass das nicht zu einem Problem geführt hat.

Es geht dir vermutlich um das hier:
https://github.com/alexplusde/speed_up/blob/22cf2dc25536f3b14b7d08012d0ab24d7815b302/lib/speed_up.php#L38-L41

Seiten-Startartikel sollte eigentlich kein Problem sein. In einer Multidomain-Umgebung muss man halt aufpassen, nicht falsch abzubiegen und Seiten anderer Domains zu prefetchen.

**Comment by ynamite** [comment]
Bei mir wird auf der Startseite nichts ausgeben, in normalen Kategorien gibt es ausschliesslich ein prefetch auf die Startseite, sonst nichts, unabhängig von der gewählten Einstellung. 
Sollten nicht wenigstens die Hauptkategorien auch prefetched werden? Ich habe 4 Kategorien in der Hauptebene jeweils ohne Unterkategorien.

Ich meine das hier ist verantwortlich:
https://github.com/alexplusde/speed_up/blob/22cf2dc25536f3b14b7d08012d0ab24d7815b302/lib/speed_up.php#LL16-L26C10

Ich habe diese Zeilen wie folgt angepasst. Nun tut es das, was (zumindest) ich erwartet hätte:
```
        $category_children = rex_category::getRootCategories(true);
        $category_parent = null;
        $category_articles = rex_article::getRootArticles(true);
        $category_current_prio = 0;

        if ($category_current) {
            $category_children = array_merge($category_children, $category_current->getChildren(true));
            $category_parent = $category_current->getParent();
            $category_articles = array_merge($category_articles, $category_current->getArticles(true));
            $category_current_prio = $category_current->getPriority();
        }  
```

Vielleicht ist das aber gar nicht so gewollt. Daher auch die ursprüngliche Frage, ob ich etwas falsch mache.

**Comment by ynamite** [comment]
Richtig, bei mir ist die Startseite eine Kategorie/Menüpunkt. Aber ist die Mountpoint-Ebene nicht oftmals zugleich die Hauptebene?

Jedenfalls funzt das wie gesagt bei mir nicht, selbst mit "aggressiv" als Einstellung.

Ich bin der Meinung, dass Kategorien/Artikel aus der Mountpoint-Ebene immer ein preload erfahren sollten. Denn nur weil ich mich in einer Kategorie mit Unterkategorien und -Artikeln befinde, heisst das ja nicht zwangsläufig, dass ich nur immer tiefer gehe.

**Comment by alxndr-w** [comment]
Deswegen sollte auch eine Ebene höher geschaut werden. 

Ich werde es mir mal anschauen - für ein Addon, das in wenigen Stunden nebenbei entstanden ist, gibt's ja scheinbar ein wenig Nachfrage.

Deine gewünschten Kategorien per EP einzuhängen hat nicht geklappt? (Den habe ich extra für solche Wünsche eingebaut, aber nie getestet / im Einsatz gehabt)

**Comment by ynamite** [comment]
EP habe ich gar nicht ausprobiert. Die initiale Frage war ja, ob das so gedacht ist (dass das Addon nix tut). 
Denn gemäss Doku muss man ja nichts weiter tun, als den Aufruf in den HTML Head zu schreiben.

Vorerst lasse ich mal meinen Code laufen, der tut was ich möchte :)

**Comment by alxndr-w** [comment]
Da hast du recht. Das sollte den Fall Startseite unterhalb Mountpoint auf jeden Fall berücksichtigen. Aber ob man aus Ebene 3 wirklich noch Ebene 1 vorladen soll... eher nicht.

Wenn du SEO-mäßig Dinge verbessern willst, dann weißt du ja, dass es eher um Assets und Co. geht.

**Comment by ynamite** [comment]
Wieso denkst du nicht? Ich hätte jetzt gesagt, ohne Daten zum Nutzerverhalten zu haben, dass Nutzer tendenziell eher die Ebene 1 durchklicken, egal wie tief sie sich bereits befinden, statt auf Ebene X weiterzuklicken.

Nö, nicht wegen SEO, eher wegen User-Experience.

**Comment by alxndr-w** [comment]
Mir schwebte eher vor, dass ein Prefetch stattfindet, wenn man bspw. mit der Maus oder mit dem Viewport über einen Menüpunkt fährt. Quasi onhover. Dann wäre es noch dynamischer und man müsste nicht auf gut Glück die halbe Seite prefetchen. Ziel für mich war eigentlich, maximal 5 Links pro Seite zu prefetchen.
