### ISSUE TITLE
PHP Fehlermeldungen

### ISSUE THREAD

**Issue by iceman-fx** [alexplusde/speed_up#34]
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in redaxo\src\addons\speed_up\lib\speed_up.php on line 44
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in redaxo\src\addons\speed_up\lib\speed_up.php on line 176

PHP 8.1

**Comment by alxndr-w** [comment]
Das dürfte einfach zu beheben sein, gerne direkt einen PR einreichen.

**Comment by alxndr-w** [comment]
Ich finde es immer schade, dass man sich die Mühe macht, ein Issue hier aufzumachen und es in etwa genau so viel Zeit benötigt, hier in der Weboberfläche einen Patch einzureichen. Woran liegt's?
