### ISSUE TITLE
Für den Einbau ins Template eine eigene REX_VAR nehmen?

### ISSUE THREAD

**Issue by tyrant88** [alexplusde/speed_up#9]
Sowas wie REX_SPEED_UP[] ? Wobei ich REX_PREFETCH_LINKS[] bevorzugen würde.

**Comment by alxndr-w** [comment]
Ja, gerne. Ich würde auch unterscheiden wollen mittelfristig zwischen preload und prefetch mit eigenen Einstellungsseiten und eigenen Codes.
